### ISSUE TITLE
username as dynamic property in storage plugin

### ISSUE THREAD

**Issue by Z0ltrix** [apache/drill#2296]
**Is your feature request related to a problem? Please describe.**
I would like to use Phoenix-Queryserver with active impersonation through jdbc storage plugin in drill.

At the moment we got phoenix-queryserver to work with kerberos auth and a specific keytab for drill. Drill is configured with active impersonation, so if Bob submits a query to drill, drill impersonates Bob agains HDFS and HBase.

Because of the fixed keytab and principals in jdbc string, all queries against phoenix are submitted with the user specified at the keytab.

To fulfill all security requirements we need active impersonation against phoenix.

**Describe the solution you'd like**
I would like to specify the original username of the drill query in the connection string of the jdbc storage plugin, as it is described here: https://phoenix.apache.org/server.html#Impersonation 

``` 
{
  "type": "jdbc",
  "driver": "org.apache.phoenix.queryserver.client.Driver",
  "url": "jdbc:phoenix:thin:url=http://localhost:8765?doAs=$user;serialization=PROTOBUF;authentication=SPNEGO;principal=drill/bit@MY.CLUSTER;keytab=/etc/hadoop/conf/drill.keytab",
  "username": null,
  "password": null,
  "caseInsensitiveTableNames": false,
  "enabled": true
}
```

If Bob sends a Query like `SELECT * FROM phoenix.schema.table` drill should sends the query with doAs=Bob

**Describe alternatives you've considered**
none

**Additional context**
If i try to update the current configuration with the above example i get following error:
```
Please retry: Error while creating / updating storage : Remote driver error: RuntimeException: org.apache.phoenix.exception.PhoenixIOException: 
org.apache.hadoop.hbase.security.AccessDeniedException: Insufficient permissions (user=$user, scope=SYSTEM:CATALOG, params=[table=SYSTEM:CATALOG],action=EXEC) 
 at org.apache.hadoop.hbase.security.access.AccessChecker.requirePermission(AccessChecker.java:127) 
 at org.apache.hadoop.hbase.security.access.AccessController.requirePermission(AccessController.java:425) 
 at org.apache.hadoop.hbase.security.access.AccessController.preEndpointInvocation(AccessController.java:2123) 
 at org.apache.hadoop.hbase.regionserver.RegionCoprocessorHost$69.call(RegionCoprocessorHost.java:1667) 
 at org.apache.hadoop.hbase.regionserver.RegionCoprocessorHost$EndpointOperation.call(RegionCoprocessorHost.java:1771) 
 at org.apache.hadoop.hbase.regionserver.RegionCoprocessorHost.execOperation(RegionCoprocessorHost.java:1827) 
 at org.apache.hadoop.hbase.regionserver.RegionCoprocessorHost.execOperationWithResult(RegionCoprocessorHost.java:1810) 
 at org.apache.hadoop.hbase.regionserver.RegionCoprocessorHost.preEndpointInvocation(RegionCoprocessorHost.java:1662) 
 at org.apache.hadoop.hbase.regionserver.HRegion.execService(HRegion.java:8518) 
 at org.apache.hadoop.hbase.regionserver.RSRpcServices.execServiceOnRegion(RSRpcServices.java:2282) 
 at org.apache.hadoop.hbase.regionserver.RSRpcServices.execService(RSRpcServices.java:2264) 
 at org.apache.hadoop.hbase.protobuf.generated.ClientProtos$ClientService$2.callBlockingMethod(ClientProtos.java:36808) 
 at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:2399) 
 at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:124) 
 at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:311) 
 at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:291) -> PhoenixIOException: org.apache.hadoop.hbase.security.AccessDeniedException: Insufficient permissions (user=$user, scope=SYSTEM:CATALOG, params=[table=SYSTEM:CATALOG],action=EXEC) 
 at org.apache.hadoop.hbase.security.access.AccessChecker.requirePermission(AccessChecker.java:127) 
 at org.apache.hadoop.hbase.security.access.AccessController.requirePermission(AccessController.java:425) 
 at org.apache.hadoop.hbase.security.access.AccessController.preEndpointInvocation(AccessController.java:2123) 
 at org.apache.hadoop.hbase.regionserver.RegionCoprocessorHost$69.call(RegionCoprocessorHost.java:1667) 
 at org.apache.hadoop.hbase.regionserver.RegionCoprocessorHost$EndpointOperation.call(RegionCoprocessorHost.java:1771) 
 at org.apache.hadoop.hbase.regionserver.RegionCoprocessorHost.execOperation(RegionCoprocessorHost.java:1827) 
 at org.apache.hadoop.hbase.regionserver.RegionCoprocessorHost.execOperationWithResult(RegionCoprocessorHost.java:1810) 
 at org.apache.hadoop.hbase.regionserver.RegionCoprocessorHost.preEndpointInvocation(RegionCoprocessorHost.java:1662) 
 at org.apache.hadoop.hbase.regionserver.HRegion.execService(HRegion.java:8518) 
 at org.apache.hadoop.hbase.regionserver.RSRpcServices.execServiceOnRegion(RSRpcServices.java:2282) 
 at org.apache.hadoop.hbase.regionserver.RSRpcServices.execService(RSRpcServices.java:2264) 
 at org.apache.hadoop.hbase.protobuf.generated.ClientProtos$ClientService$2.callBlockingMethod(ClientProtos.java:36808) 
 at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:2399) 
 at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:124) 
 at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:311) 
 at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:291) -> AccessDeniedException: org.apache.hadoop.hbase.security.AccessDeniedException: Insufficient permissions (user=$user, scope=SYSTEM:CATALOG, params=[table=SYSTEM:CATALOG],action=EXEC) 
 at org.apache.hadoop.hbase.security.access.AccessChecker.requirePermission(AccessChecker.java:127) 
 at org.apache.hadoop.hbase.security.access.AccessController.requirePermission(AccessController.java:425) 
 at org.apache.hadoop.hbase.security.access.AccessController.preEndpointInvocation(AccessController.java:2123) 
 at org.apache.hadoop.hbase.regionserver.RegionCoprocessorHost$69.call(RegionCoprocessorHost.java:1667) 
 at org.apache.hadoop.hbase.regionserver.RegionCoprocessorHost$EndpointOperation.call(RegionCoprocessorHost.java:1771) 
 at org.apache.hadoop.hbase.regionserver.RegionCoprocessorHost.execOperation(RegionCoprocessorHost.java:1827) 
 at org.apache.hadoop.hbase.regionserver.RegionCoprocessorHost.execOperationWithResult(RegionCoprocessorHost.java:1810) 
 at org.apache.hadoop.hbase.regionserver.RegionCoprocessorHost.preEndpointInvocation(RegionCoprocessorHost.java:1662) 
 at org.apache.hadoop.hbase.regionserver.HRegion.execService(HRegion.java:8518) 
 at org.apache.hadoop.hbase.regionserver.RSRpcServices.execServiceOnRegion(RSRpcServices.java:2282) 
 at org.apache.hadoop.hbase.regionserver.RSRpcServices.execService(RSRpcServices.java:2264) 
 at org.apache.hadoop.hbase.protobuf.generated.ClientProtos$ClientService$2.callBlockingMethod(ClientProtos.java:36808) 
 at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:2399) 
 at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:124) 
 at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:311) 
 at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:291) -> RemoteWithExtrasException: org.apache.hadoop.hbase.security.AccessDeniedException: Insufficient permissions (user=$user, scope=SYSTEM:CATALOG, params=[table=SYSTEM:CATALOG],action=EXEC) 
 at org.apache.hadoop.hbase.security.access.AccessChecker.requirePermission(AccessChecker.java:127) 
 at org.apache.hadoop.hbase.security.access.AccessController.requirePermission(AccessController.java:425) 
 at org.apache.hadoop.hbase.security.access.AccessController.preEndpointInvocation(AccessController.java:2123) 
 at org.apache.hadoop.hbase.regionserver.RegionCoprocessorHost$69.call(RegionCoprocessorHost.java:1667) 
 at org.apache.hadoop.hbase.regionserver.RegionCoprocessorHost$EndpointOperation.call(RegionCoprocessorHost.java:1771) 
 at org.apache.hadoop.hbase.regionserver.RegionCoprocessorHost.execOperation(RegionCoprocessorHost.java:1827) 
 at org.apache.hadoop.hbase.regionserver.RegionCoprocessorHost.execOperationWithResult(RegionCoprocessorHost.java:1810) 
 at org.apache.hadoop.hbase.regionserver.RegionCoprocessorHost.preEndpointInvocation(RegionCoprocessorHost.java:1662) 
 at org.apache.hadoop.hbase.regionserver.HRegion.execService(HRegion.java:8518) 
 at org.apache.hadoop.hbase.regionserver.RSRpcServices.execServiceOnRegion(RSRpcServices.java:2282) 
 at org.apache.hadoop.hbase.regionserver.RSRpcServices.execService(RSRpcServices.java:2264) 
 at org.apache.hadoop.hbase.protobuf.generated.ClientProtos$ClientService$2.callBlockingMethod(ClientProtos.java:36808) 
 at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:2399) 
 at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:124) 
 at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:311) 
 at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:291)
```
So we can see that Phoenix Queryserver tries to impersonate, but got the fix string `$user`

**Comment by luocooong** [comment]
@Z0ltrix Thanks for the idea. As I understand it, need Drill to know who sent this request. Drill executes client requests as the user logged in to the client ([Authentication](https://drill.apache.org/docs/securing-drill-introduction/) support the PAM and Kerberos if [Impersonation](https://drill.apache.org/docs/configuring-user-impersonation/) is configured). So, user can passes the query request (and the user credentials) to storage layer once successfully login in the drill use the PAM (or krb ?). But, neither PAM nor Kerberos may be a direct user on the application layer. In other words, both PAM and Kerberos are not flexible in setup.

**Comment by Z0ltrix** [comment]
Hi @luocooong,

ok, understood that storage plugin is loaded by drill itself before user logs in. So there is no way to specify it at the plugin config.
Is there any other way to do this at query time?

How is Impersonation handled for hdfs and hbase?

Im open for everything else that gets the initial idea to work. Maybe we should rename the feature request to "jdbc impersonation support" or something else.

**Comment by cgivre** [comment]
Hi Christian, 
I think this actually might be a very easy fix. 

Good News:  As part of DRILL-7855 [1] we introduced a password vault to Drill which enables user impersonation for all storage plugins.  Here is the documentation for this feature [2].

Not Great News:  I'm not exactly sure whether this was enabled for the JDBC plugin.  If it isn't, it is not that difficult to add this to the config for any plugin. 


1: https://github.com/apache/drill/pull/2162 <https://github.com/apache/drill/pull/2162>
2.: https://github.com/apache/drill/blob/master/docs/dev/PluginCredentialsProvider.md <https://github.com/apache/drill/blob/master/docs/dev/PluginCredentialsProvider.md>

Best,
-- C

**Comment by Z0ltrix** [comment]
Hi @cgivre ,

yes i saw this new feature, but i have not found any hint on how to forward the currently impersonated enduser by drill to the storage plugin.

I dont want do specify the username at the plugin, i want to impersonate the enduser directly to the storage plugin.

Im not sure if i missed something but maybe you can guide me to the right lines in code or give me an config example for this.
