### ISSUE TITLE
Embedded startup with kerberos error

### ISSUE THREAD

**Issue by riritack** [apache/drill#2314]
i have configured the drill-override.conf
```
drill.exec: {
  cluster-id: "drillbits1",
  zk.connect: "localhost:2181",
  impersonation {
    enabled: true,
    max_chained_user_hops: 3
  },
  security: {
                user.auth.enabled: true,
                auth.mechanisms: ["KERBEROS"],
                auth.principal: "hbase/cdh01..com@XXX.COM",
                auth.keytab: "/root/hbase.keytab" ,
                user.encryption.sasl.enabled: true
              }
}
```
but when i run embedded it broken like that 
```
java.sql.SQLException: Failure in starting embedded Drillbit: org.apache.drill.exec.exception.DrillbitStartupException: Authentication is enabled for WebServer but none of the security mechanism was configured properly. Please verify the configurations and try again.
	at org.apache.drill.jdbc.impl.DrillConnectionImpl.<init>(DrillConnectionImpl.java:131)
	at org.apache.drill.jdbc.impl.DrillJdbc41Factory.newDrillConnection(DrillJdbc41Factory.java:67)
	at org.apache.drill.jdbc.impl.DrillFactory.newConnection(DrillFactory.java:67)
	at org.apache.calcite.avatica.UnregisteredDriver.connect(UnregisteredDriver.java:138)
	at org.apache.drill.jdbc.Driver.connect(Driver.java:75)
	at sqlline.DatabaseConnection.connect(DatabaseConnection.java:135)
	at sqlline.DatabaseConnection.getConnection(DatabaseConnection.java:192)
	at sqlline.Commands.connect(Commands.java:1364)
	at sqlline.Commands.connect(Commands.java:1244)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sqlline.ReflectiveCommandHandler.execute(ReflectiveCommandHandler.java:38)
	at sqlline.SqlLine.dispatch(SqlLine.java:730)
	at sqlline.SqlLine.initArgs(SqlLine.java:410)
	at sqlline.SqlLine.begin(SqlLine.java:515)
	at sqlline.SqlLine.start(SqlLine.java:267)
	at sqlline.SqlLine.main(SqlLine.java:206)
Caused by: org.apache.drill.exec.exception.DrillbitStartupException: Authentication is enabled for WebServer but none of the security mechanism was configured properly. Please verify the configurations and try again.
	at org.apache.drill.exec.server.rest.auth.DrillHttpSecurityHandlerProvider.<init>(DrillHttpSecurityHandlerProvider.java:108)
	at org.apache.drill.exec.server.rest.WebServer.createServletContextHandler(WebServer.java:227)
	at org.apache.drill.exec.server.rest.WebServer.start(WebServer.java:154)
	at org.apache.drill.exec.server.Drillbit.run(Drillbit.java:234)
	at org.apache.drill.jdbc.impl.DrillConnectionImpl.<init>(DrillConnectionImpl.java:122)
	... 18 more
```

what other flies need i to confgure to solve it

**Comment by luocooong** [comment]
@riritack Hi, would you mind telling me the issue is solved or not?
