### ISSUE TITLE
1.20.0-SNAPSHOT Fails on mongodb cluster query

### ISSUE THREAD

**Issue by javier-nieto-nexplore** [apache/drill#2355]
**Describe the bug**
Drill is not able to query mongodb cluster, it throws a NPE

```
2021-10-28 16:21:52,535 [1e8531df-4e21-f062-707b-b9cbb72c619e:foreman] INFO  o.a.d.e.s.mongo.MongoStoragePlugin - Created srv protocol connection to [address=mongoclusterDNSisOK:27017, user=USERalsoOK].
2021-10-28 16:21:52,535 [1e8531df-4e21-f062-707b-b9cbb72c619e:foreman] INFO  o.a.d.e.s.mongo.MongoStoragePlugin - Number of open connections 1.
2021-10-28 16:21:53,165 [1e8531df-4e21-f062-707b-b9cbb72c619e:foreman] WARN  o.a.d.e.s.m.s.MongoSchemaFactory - Failure while getting collection names from 'config'. Command failed with error 13 (Unauthorized): 'not authorized on config to execute command ...
2021-10-28 16:21:53,208 [1e8531df-4e21-f062-707b-b9cbb72c619e:foreman] WARN  o.a.d.e.s.m.s.MongoSchemaFactory - Failure while getting collection names from 'local'. Command failed with error 13 (Unauthorized): 'not authorized on local to execute command ...
2021-10-28 16:21:58,711 [1e8531df-4e21-f062-707b-b9cbb72c619e:frag:1:0] INFO  o.a.d.e.w.fragment.FragmentExecutor - 1e8531df-4e21-f062-707b-b9cbb72c619e:1:0: State change requested AWAITING_ALLOCATION --> FINISHED
2021-10-28 16:21:58,711 [1e8531df-4e21-f062-707b-b9cbb72c619e:frag:1:0] INFO  o.a.d.e.w.f.FragmentStatusReporter - 1e8531df-4e21-f062-707b-b9cbb72c619e:1:0: State to report: FINISHED
2021-10-28 16:21:58,711 [drill-executor-6] ERROR o.a.d.exec.server.BootStrapContext - org.apache.drill.exec.work.WorkManager$WorkerBee$1.run() leaked an exception.
java.lang.NullPointerException: null
	at org.apache.drill.exec.work.fragment.FragmentExecutor.run(FragmentExecutor.java:347)
	at org.apache.drill.common.SelfCleaningRunnable.run(SelfCleaningRunnable.java:38)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```
The DBs unauthorized are cluster-private stuff, these warning lines are also as DEBUG at 1.18.0 logs but after the query is starting on the requested DB without problems.

**To Reproduce**
1. Create a mongodb cluster storage
2. Try a query
3. Check the logs

**Expected behavior**
Running the query

**Additional context**
[version] apache/drill:master-openjdk-14
[DIGEST] 55e6551a8523 (2021/10/28 5:23pm)
[OS] docker

**Comment by luocooong** [comment]
<pre>
apache drill> show databases;
+-----------------------------+
|         SCHEMA_NAME         |
+-----------------------------+
| cp.default                  |
| dfs.default                 |
| dfs.root                    |
| dfs.tmp                     |
| information_schema          |
| mongo_atlas.admin           |
| mongo_atlas.local           |
| mongo_atlas.myfirstdatabase |
| sys                         |
+-----------------------------+
9 rows selected (0.318 seconds)

apache drill> use mongo_atlas.myfirstdatabase;
+------+---------------------------------------------------------+
|  ok  |                         summary                         |
+------+---------------------------------------------------------+
| true | Default schema changed to [mongo_atlas.myfirstdatabase] |
+------+---------------------------------------------------------+
1 row selected (0.099 seconds)

apache drill (mongo_atlas.myfirstdatabase)> show tables;
+-----------------------------+------------+
|        TABLE_SCHEMA         | TABLE_NAME |
+-----------------------------+------------+
| mongo_atlas.myfirstdatabase | test       |
+-----------------------------+------------+
1 row selected (0.248 seconds)

apache drill (mongo_atlas.myfirstdatabase)> select * from test;
+-----------------------------+-------------------------+
|             _id             |          date           |
+-----------------------------+-------------------------+
| a"j\xC3;)\xFFc\x06\xB3j\xA9 | 2021-08-22 23:18:27.258 |
+-----------------------------+-------------------------+
1 row selected (2.196 seconds)
</pre>

@javier-nieto-nexplore I cannot reproduce the same set of problems on the cluster (3.6, replica set) and Atlas cloud (4.4, free). I think the difference is `Database Access` :

User Name | Authentication Method | MongoDB Roles | Resources 
-- | -- | -- | --
test | SCRAM | atlasAdmin@admin | All Resources

**Comment by javier-nieto-nexplore** [comment]
Hi @luocooong 

Tested with admin user an same result, I would say it could be something about collection size.
I've just done these tests:

1. silly collection with 1 field -> OK
2. complex collection (flat document) with 10K docs -> OK
3. complex collection (flat doc) with 160K docs -> NPE

**Comment by luocooong** [comment]
@javier-nieto-nexplore Thanks for the explanation. Could you please post the log file (as an attachment)? Please mask any privacy information, thanks.

**Comment by javier-nieto-nexplore** [comment]
Hi @luocooong 

logs are a bit dry :( but I realized that this is related to a config param (planner.slice_target), looks like it has to be greater than collection doc count, not tested in dist mode though

![image](https://user-images.githubusercontent.com/83208332/140080676-2cdfab2c-a5d0-41a6-b02a-934dc5c473fb.png)

```
2021-11-03 14:27:40,553 [1e7d63a2-9c2f-c629-d5f1-50c47d2ff3b1:foreman] INFO  o.a.drill.exec.work.foreman.Foreman - Query text for query with id 1e7d63a2-9c2f-c629-d5f1-50c47d2ff3b1 issued by anonymous: select STREET from mongo_local.fake_data_test.frisco
2021-11-03 14:27:41,848 [1e7d63a2-9c2f-c629-d5f1-50c47d2ff3b1:frag:1:0] INFO  o.a.d.e.w.fragment.FragmentExecutor - 1e7d63a2-9c2f-c629-d5f1-50c47d2ff3b1:1:0: State change requested AWAITING_ALLOCATION --> FINISHED
2021-11-03 14:27:41,848 [1e7d63a2-9c2f-c629-d5f1-50c47d2ff3b1:frag:1:0] INFO  o.a.d.e.w.f.FragmentStatusReporter - 1e7d63a2-9c2f-c629-d5f1-50c47d2ff3b1:1:0: State to report: FINISHED
2021-11-03 14:27:41,848 [drill-executor-7] ERROR o.a.d.exec.server.BootStrapContext - org.apache.drill.exec.work.WorkManager$WorkerBee$1.run() leaked an exception.
java.lang.NullPointerException: null
	at org.apache.drill.exec.work.fragment.FragmentExecutor.run(FragmentExecutor.java:347)
	at org.apache.drill.common.SelfCleaningRunnable.run(SelfCleaningRunnable.java:38)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by cgivre** [comment]
@javier-nieto-nexplore 
It might be good to document this in the Drill docs.

**Comment by javier-nieto-nexplore** [comment]
@cgivre  do you think it's the expected behavior?

**Comment by cgivre** [comment]
@javier-nieto-nexplore 
I guess my question is does this fix the issue when you change the setting?  If so, then we should document this and tell the user that if you have a collection with more documents than the planner slice target allows, you should increase that.  I am curious as to how running this in distributed mode affects this issue. 

IMHO, regardless, we should improve the error message so that if this happens, a user knows how to fix it.

**Comment by javier-nieto-nexplore** [comment]
Hi @cgivre fully agree NPE is not a great hint, it took me some time to find a trail

we can note down this as a known issue but for me that's not an 100% acceptable solution, how high should you go with the slice_target to cover your needs i.e.:1M,10M? 

also I'm a bit concerned about possible the side effects as we don't know the root cause of the issue.

**Comment by javier-nieto-nexplore** [comment]
Hi @luocooong here's some log with several query runs vs. local mongo with dummy data, changing the slice_target parameter made it OK/KO and going through the MongoScanBatchCreator log or not, also the fragment id has some 1:0/0:0

Hope it helps

[error_log.txt](https://github.com/apache/drill/files/7512629/error_log.txt)
