### ISSUE TITLE
What is the tag check function? what does tag of 10 and 84 mean in the check?

### ISSUE THREAD

**Issue by a484771** [apache/drill#2482]
Hi Team I meet the below error when I use drill maven dependency version 1.17.0, I deployed drill on EKS and it works when I port-forward the service, but after I config an ALB ingress, the error occurred (the same ALB ingress config works for port 8047 so I can see the UI, but not working for 31010), the message is not very comprehensive, so anyone please help to explain, what does 10 and 84 as tag mean? Thanks

2022-03-04 20:01:25.194 ERROR 53489 --- [       Client-1] o.o.a.d.exec.rpc.RpcExceptionHandler     : Exception in RPC communication.  Connection: /10.179.34.218:56013 <--> apache-drill-ui.some-ingress-path/10.225.132.104:80 (user client).  Closing connection.

oadd.io.netty.handler.codec.CorruptedFrameException: Expected to read a tag of 10 but actually received a value of 84.  Happened after reading 0 message.
        at oadd.org.apache.drill.exec.rpc.RpcDecoder.checkTag(RpcDecoder.java:126) ~[drill-jdbc-all-1.17.0.jar!/:1.17.0]
        at oadd.org.apache.drill.exec.rpc.RpcDecoder.decode(RpcDecoder.java:61) ~[drill-jdbc-all-1.17.0.jar!/:1.17.0]
        at oadd.org.apache.drill.exec.rpc.RpcDecoder.decode(RpcDecoder.java:35) ~[drill-jdbc-all-1.17.0.jar!/:1.17.0]

And the ALB config is as below:
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/security-groups: EKS-ALB-sg
    alb.ingress.kubernetes.io/success-codes: 200-499
    alb.ingress.kubernetes.io/tags: Environment=dev,Team=EKSAdminTeam
    alb.ingress.kubernetes.io/target-type: 'ip'
    kubernetes.io/ingress.class: alb
  name: ingress-2
spec:
  rules:
  - host: -----
    http:
      paths:
        - backend:
            serviceName: drill-service
            servicePort: 31010
          path: /*

**Comment by jnturton** [comment]
The problem here might be that the comms on port 31010 is not HTTP.

**Comment by a484771** [comment]
>
