### ISSUE TITLE
Translation of IS NOT NULL($1) is not supported by MongoProject

### ISSUE THREAD

**Issue by shashankjiffy** [apache/drill#2563]
During execution of COALESCE function when used along with any hard coded value e.g. sdfsafdsd along with the column name..getting error.

**To Reproduce**
1. Query `SELECT
  `COALESCE`(`Filename`,'sdfsafdsd') 
FROM
dd7819ee-438e-429b-9a3a-a68c7f1cc123

LIMIT 500`
2. Executing above query 
3. See error
![image](https://user-images.githubusercontent.com/106253817/170274561-410f7e13-609b-4d28-9c31-3e3bc3c6891c.png)

`Caused by: org.apache.drill.exec.work.foreman.ForemanException: Unexpected exception during fragment initialization: Translation of IS NOT NULL($2) is not supported by MongoProject
	at org.apache.drill.exec.work.foreman.Foreman.run(Foreman.java:301)
	at .......(:0)
Caused by: java.lang.IllegalArgumentException: Translation of IS NOT NULL($1) is not supported by MongoProject
	at org.apache.drill.exec.store.mongo.plan.RexToMongoTranslator.visitCall(RexToMongoTranslator.java:183)
	at org.apache.drill.exec.store.mongo.plan.RexToMongoTranslator.visitCall(RexToMongoTranslator.java:49)
	at org.apache.calcite.rex.RexCall.accept(RexCall.java:191)
	at org.apache.drill.exec.store.mongo.plan.RexToMongoTranslator.lambda$visitCall$0(RexToMongoTranslator.java:136)
	at .......(:0)
	at org.apache.drill.exec.store.mongo.plan.RexToMongoTranslator.visitCall(RexToMongoTranslator.java:137)
	at org.apache.drill.exec.store.mongo.plan.RexToMongoTranslator.visitCall(RexToMongoTranslator.java:49)
	at org.apache.calcite.rex.RexCall.accept(RexCall.java:191)
	at org.apache.drill.exec.store.mongo.plan.MongoPluginImplementor.implement(MongoPluginImplementor.java:150)
	at org.apache.drill.exec.store.plan.rel.PluginProjectRel.implement(PluginProjectRel.java:59)
	at org.apache.drill.exec.store.plan.PluginImplementor.visitChild(PluginImplementor.java:84)
	at org.apache.drill.exec.store.mongo.plan.MongoPluginImplementor.implement(MongoPluginImplementor.java:93)
	at org.apache.drill.exec.store.plan.rel.PluginAggregateRel.implement(PluginAggregateRel.java:59)
	at org.apache.drill.exec.store.plan.PluginImplementor.visitChild(PluginImplementor.java:84)
	at org.apache.drill.exec.store.mongo.plan.MongoPluginImplementor.implement(MongoPluginImplementor.java:173)
	at org.apache.drill.exec.store.plan.rel.PluginSortRel.implement(PluginSortRel.java:57)
	at org.apache.drill.exec.store.plan.rel.PluginPrel.<init>(PluginPrel.java:52)
	at org.apache.drill.exec.store.plan.rel.PluginIntermediatePrel.finalizeRel(PluginIntermediatePrel.java:71)
	at org.apache.drill.exec.planner.sql.handlers.DefaultSqlHandler$PrelFinalizer.visit(DefaultSqlHandler.java:322)
	at org.apache.calcite.rel.AbstractRelNode.accept(AbstractRelNode.java:272)
	at org.apache.calcite.rel.RelShuttleImpl.visitChild(RelShuttleImpl.java:55)
	at org.apache.calcite.rel.RelShuttleImpl.visitChildren(RelShuttleImpl.java:69)
	at org.apache.calcite.rel.RelShuttleImpl.visit(RelShuttleImpl.java:131)
	at org.apache.drill.exec.planner.sql.handlers.DefaultSqlHandler$PrelFinalizer.visit(DefaultSqlHandler.java:324)
	at org.apache.calcite.rel.AbstractRelNode.accept(AbstractRelNode.java:272)
	at org.apache.calcite.rel.RelShuttleImpl.visitChild(RelShuttleImpl.java:55)
	at org.apache.calcite.rel.RelShuttleImpl.visitChildren(RelShuttleImpl.java:69)
	at org.apache.calcite.rel.RelShuttleImpl.visit(RelShuttleImpl.java:131)
	at org.apache.drill.exec.planner.sql.handlers.DefaultSqlHandler$PrelFinalizer.visit(DefaultSqlHandler.java:324)
	at org.apache.calcite.rel.AbstractRelNode.accept(AbstractRelNode.java:272)
	at org.apache.drill.exec.planner.sql.handlers.DefaultSqlHandler.convertToPrel(DefaultSqlHandler.java:437)
	at org.apache.drill.exec.planner.sql.handlers.DefaultSqlHandler.getPlan(DefaultSqlHandler.java:174)
	at org.apache.drill.exec.planner.sql.DrillSqlWorker.getQueryPlan(DrillSqlWorker.java:283)
	at org.apache.drill.exec.planner.sql.DrillSqlWorker.getPhysicalPlan(DrillSqlWorker.java:163)
	at org.apache.drill.exec.planner.sql.DrillSqlWorker.convertPlan(DrillSqlWorker.java:128)
	at org.apache.drill.exec.planner.sql.DrillSqlWorker.getPlan(DrillSqlWorker.java:93)
	at org.apache.drill.exec.work.foreman.Foreman.runSQL(Foreman.java:593)
	at org.apache.drill.exec.work.foreman.Foreman.run(Foreman.java:274)
	... 1 common frames omitted`

Note : Version we are using is Apache Drill version : 1.20.0, this function is working fine in the 1.19.0

**Comment by cgivre** [comment]
@vvysotskyi Can this be fixed by disabling some of the pushdowns?

**Comment by vvysotskyi** [comment]
Yes, it should be enough to disable project push down

**Comment by jnturton** [comment]
Promoted to [DRILL-8238](https://issues.apache.org/jira/browse/DRILL-8238).

**Comment by jnturton** [comment]
@shashankjiffy a fix for this bug will be included in Drill 1.20.3
